/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Proses hidup. Dipakai load balancer dan liveness probe.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description Siap menerima traffic: database dan Redis terhubung.
         */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Cabut refresh token. Access token yang sudah terbit tetap berlaku sampai kedaluwarsa.
         */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Me
         * @description Profil user yang sedang login (MCP tool: get_my_profile).
         */
        get: operations["get_me_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/org-units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Org Units
         * @description Struktur organisasi. Bisa dilihat semua role.
         */
        get: operations["list_org_units_org_units_get"];
        put?: never;
        /** Create Org Unit */
        post: operations["create_org_unit_org_units_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/org-units/{unit_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Org Unit */
        get: operations["get_org_unit_org_units__unit_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Org Unit */
        patch: operations["update_org_unit_org_units__unit_id__patch"];
        trace?: never;
    };
    "/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Employees
         * @description Daftar karyawan beserta jabatan yang berlaku (MCP tool: list_employees, khusus HR).
         */
        get: operations["list_employees_employees_get"];
        put?: never;
        /** Create Employee */
        post: operations["create_employee_employees_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/{employee_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Employee
         * @description HR: semua karyawan. Karyawan: dirinya sendiri. Atasan: bawahan langsung.
         */
        get: operations["get_employee_employees__employee_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Employee */
        patch: operations["update_employee_employees__employee_id__patch"];
        trace?: never;
    };
    "/employees/{employee_id}/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Jobs
         * @description Riwayat jabatan, terbaru dulu. HR atau karyawan itu sendiri.
         */
        get: operations["list_jobs_employees__employee_id__jobs_get"];
        put?: never;
        /**
         * Add Job
         * @description Mutasi, promosi, perubahan data, berhenti, atau rehire. Riwayat lama tidak diubah.
         */
        post: operations["add_job_employees__employee_id__jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leave/types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Leave Types
         * @description Tipe cuti untuk form pengajuan. include_inactive hanya berlaku untuk HR.
         */
        get: operations["list_leave_types_leave_types_get"];
        put?: never;
        /** Create Leave Type */
        post: operations["create_leave_type_leave_types_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leave/types/{type_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Leave Type
         * @description Tipe cuti tidak dihapus, cukup dinonaktifkan (is_active=false) supaya histori utuh.
         */
        patch: operations["update_leave_type_leave_types__type_id__patch"];
        trace?: never;
    };
    "/leave/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Policies */
        get: operations["list_policies_leave_policies_get"];
        put?: never;
        /** Create Policy */
        post: operations["create_policy_leave_policies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leave/policies/{policy_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Policy */
        delete: operations["delete_policy_leave_policies__policy_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Policy
         * @description Berlaku untuk saldo yang dibuat setelah ini. Saldo yang sudah ada tidak berubah.
         */
        patch: operations["update_policy_leave_policies__policy_id__patch"];
        trace?: never;
    };
    "/leave/holidays": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Holidays
         * @description Hari libur nasional, cuti bersama, dan libur perusahaan. Default tahun berjalan.
         */
        get: operations["list_holidays_leave_holidays_get"];
        put?: never;
        /** Create Holiday */
        post: operations["create_holiday_leave_holidays_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leave/holidays/{holiday_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Holiday
         * @description Pengajuan yang sudah dibuat tidak dihitung ulang.
         */
        delete: operations["delete_holiday_leave_holidays__holiday_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leave/balances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Leave Balance
         * @description Saldo cuti per tipe (MCP tool: get_leave_balance). Default: diri sendiri, tahun berjalan.
         *     HR bisa melihat siapa saja, atasan bisa melihat bawahan langsung.
         */
        get: operations["get_leave_balance_leave_balances_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leave/balances/adjustments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Adjust Leave Balance
         * @description Koreksi saldo manual oleh HR, misal saldo awal dari sistem lama. Tercatat di audit_log.
         */
        post: operations["adjust_leave_balance_leave_balances_adjustments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leave/requests/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate Leave Request
         * @description Dry-run (MCP tool: validate_leave_request). Tidak menyimpan apa pun. Form dan chat
         *     memakai endpoint ini, jadi aturannya sama persis dengan submit.
         */
        post: operations["validate_leave_request_leave_requests_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leave/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Leave Requests
         * @description MCP tool: list_leave_requests. mine: pengajuan sendiri. approvals: menunggu keputusan
         *     saya. all: semua pengajuan (HR). Default tahun berjalan, kecuali approvals.
         */
        get: operations["list_leave_requests_leave_requests_get"];
        put?: never;
        /**
         * Submit Leave Request
         * @description Ajukan cuti (MCP tool: submit_leave_request, wajib konfirmasi user). Idempotency-Key
         *     yang sama mengembalikan pengajuan yang sudah ada, jadi retry tidak membuat dobel.
         */
        post: operations["submit_leave_request_leave_requests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leave/requests/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Leave Request
         * @description Pemohon, approver pengajuan itu, dan HR.
         */
        get: operations["get_leave_request_leave_requests__request_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leave/requests/{request_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Leave Request
         * @description MCP tool: cancel_leave_request (wajib konfirmasi user). Pemohon atau HR, sebelum cuti
         *     dimulai. Saldo dikembalikan di transaksi yang sama.
         */
        post: operations["cancel_leave_request_leave_requests__request_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leave/requests/{request_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decide Leave Request
         * @description MCP tool: decide_leave_request (wajib konfirmasi user). Approver di level berjalan,
         *     atau HR untuk level mana pun (termasuk level tanpa atasan).
         */
        post: operations["decide_leave_request_leave_requests__request_id__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leave/team-calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Team Calendar
         * @description MCP tool: get_team_calendar. Cuti pending dan approved di rentang tanggal (maks 93 hari).
         *     Atasan: bawahan langsung. HR: semua, opsional per unit.
         */
        get: operations["get_team_calendar_leave_team_calendar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ApprovalStatus
         * @enum {string}
         */
        ApprovalStatus: "pending" | "approved" | "rejected" | "skipped";
        /**
         * BalanceAdjustment
         * @description Koreksi saldo manual oleh HR (misal saldo awal migrasi dari sistem lama).
         */
        BalanceAdjustment: {
            /**
             * Employee Id
             * Format: uuid
             */
            employee_id: string;
            /**
             * Leave Type Id
             * Format: uuid
             */
            leave_type_id: string;
            /** Year */
            year: number;
            /** Delta */
            delta: number;
            /** Note */
            note: string;
        };
        /** BalancePreview */
        BalancePreview: {
            /** Available Before */
            available_before: number;
            /** Available After */
            available_after: number;
        };
        /** CurrentJob */
        CurrentJob: {
            /**
             * Effdt
             * Format: date
             */
            effdt: string;
            /** Effseq */
            effseq: number;
            action: components["schemas"]["JobAction"];
            /** Job Title */
            job_title: string;
            /** Grade */
            grade: string;
            /**
             * Org Unit Id
             * Format: uuid
             */
            org_unit_id: string;
            /** Supervisor Employee Id */
            supervisor_employee_id: string | null;
            employment_type: components["schemas"]["EmploymentType"];
            employment_status: components["schemas"]["EmploymentStatus"];
        };
        /**
         * EmployeeCreate
         * @description Membuat karyawan sekaligus riwayat jabatan pertama (aksi 'hire' per hire_date).
         */
        EmployeeCreate: {
            /** Employee Number */
            employee_number: string;
            /** Full Name */
            full_name: string;
            /** Work Email */
            work_email?: string | null;
            /**
             * Hire Date
             * Format: date
             */
            hire_date: string;
            job: components["schemas"]["JobFields"];
        };
        /**
         * EmployeeJobCreate
         * @description Field jabatan yang tidak dikirim diambil dari riwayat yang berlaku per effdt.
         */
        EmployeeJobCreate: {
            /**
             * Effdt
             * Format: date
             */
            effdt: string;
            action: components["schemas"]["JobAction"];
            /** Reason */
            reason?: string | null;
            /** Job Title */
            job_title?: string | null;
            /** Grade */
            grade?: string | null;
            /** Org Unit Id */
            org_unit_id?: string | null;
            /** Supervisor Employee Id */
            supervisor_employee_id?: string | null;
            employment_type?: components["schemas"]["EmploymentType"] | null;
        };
        /** EmployeeJobRead */
        EmployeeJobRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Effdt
             * Format: date
             */
            effdt: string;
            /** Effseq */
            effseq: number;
            action: components["schemas"]["JobAction"];
            /** Reason */
            reason: string | null;
            /** Job Title */
            job_title: string;
            /** Grade */
            grade: string;
            /**
             * Org Unit Id
             * Format: uuid
             */
            org_unit_id: string;
            /** Supervisor Employee Id */
            supervisor_employee_id: string | null;
            employment_type: components["schemas"]["EmploymentType"];
            employment_status: components["schemas"]["EmploymentStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** EmployeeRead */
        EmployeeRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Employee Number */
            employee_number: string;
            /** Full Name */
            full_name: string;
            /** Work Email */
            work_email: string | null;
            /**
             * Hire Date
             * Format: date
             */
            hire_date: string;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "terminated" | "pre_hire";
            current_job: components["schemas"]["CurrentJob"] | null;
        };
        /**
         * EmployeeUpdate
         * @description Data dasar saja. Perubahan jabatan/unit/atasan lewat POST /employees/{id}/jobs.
         */
        EmployeeUpdate: {
            /** Full Name */
            full_name?: string | null;
            /** Work Email */
            work_email?: string | null;
        };
        /**
         * EmploymentStatus
         * @enum {string}
         */
        EmploymentStatus: "active" | "terminated";
        /**
         * EmploymentType
         * @enum {string}
         */
        EmploymentType: "permanent" | "contract" | "intern" | "daily";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Service */
            service: string;
        };
        /** HolidayCreate */
        HolidayCreate: {
            /**
             * Holiday Date
             * Format: date
             */
            holiday_date: string;
            /** Name */
            name: string;
            /** @default national */
            kind: components["schemas"]["HolidayKind"];
        };
        /**
         * HolidayKind
         * @enum {string}
         */
        HolidayKind: "national" | "collective_leave" | "company";
        /** HolidayRead */
        HolidayRead: {
            /**
             * Holiday Date
             * Format: date
             */
            holiday_date: string;
            /** Name */
            name: string;
            /** @default national */
            kind: components["schemas"]["HolidayKind"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /**
         * JobAction
         * @enum {string}
         */
        JobAction: "hire" | "rehire" | "transfer" | "promotion" | "data_change" | "termination";
        /** JobFields */
        JobFields: {
            /** Job Title */
            job_title: string;
            /** Grade */
            grade: string;
            /**
             * Org Unit Id
             * Format: uuid
             */
            org_unit_id: string;
            /** Supervisor Employee Id */
            supervisor_employee_id?: string | null;
            /** @default permanent */
            employment_type: components["schemas"]["EmploymentType"];
        };
        /** LeaveApprovalRead */
        LeaveApprovalRead: {
            /** Level */
            level: number;
            /** Approver Employee Id */
            approver_employee_id: string | null;
            status: components["schemas"]["ApprovalStatus"];
            /** Note */
            note: string | null;
            /** Decided At */
            decided_at: string | null;
        };
        /** LeaveBalanceRead */
        LeaveBalanceRead: {
            /**
             * Leave Type Id
             * Format: uuid
             */
            leave_type_id: string;
            /** Leave Type Code */
            leave_type_code: string;
            /** Leave Type Name */
            leave_type_name: string;
            /** Year */
            year: number;
            /** Entitled */
            entitled: number;
            /** Carried Over */
            carried_over: number;
            /** Adjusted */
            adjusted: number;
            /** Used */
            used: number;
            /** Pending */
            pending: number;
            /** Available */
            available: number;
        };
        /** LeaveBalanceSummary */
        LeaveBalanceSummary: {
            /**
             * Employee Id
             * Format: uuid
             */
            employee_id: string;
            /** Year */
            year: number;
            /** Items */
            items: components["schemas"]["LeaveBalanceRead"][];
        };
        /** LeaveCancel */
        LeaveCancel: {
            /** Note */
            note?: string | null;
        };
        /** LeaveDecision */
        LeaveDecision: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "approved" | "rejected";
            /** Note */
            note?: string | null;
        };
        /** LeavePolicyCreate */
        LeavePolicyCreate: {
            /**
             * Leave Type Id
             * Format: uuid
             */
            leave_type_id: string;
            /** Grade */
            grade?: string | null;
            /**
             * Min Service Months
             * @default 0
             */
            min_service_months: number;
            /** Annual Days */
            annual_days: number;
            /**
             * Max Carry Over Days
             * @default 0
             */
            max_carry_over_days: number;
            /**
             * Carry Over Expiry Months
             * @default 3
             */
            carry_over_expiry_months: number;
        };
        /** LeavePolicyRead */
        LeavePolicyRead: {
            /**
             * Leave Type Id
             * Format: uuid
             */
            leave_type_id: string;
            /** Grade */
            grade?: string | null;
            /**
             * Min Service Months
             * @default 0
             */
            min_service_months: number;
            /** Annual Days */
            annual_days: number;
            /**
             * Max Carry Over Days
             * @default 0
             */
            max_carry_over_days: number;
            /**
             * Carry Over Expiry Months
             * @default 3
             */
            carry_over_expiry_months: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** LeavePolicyUpdate */
        LeavePolicyUpdate: {
            /** Annual Days */
            annual_days?: number | null;
            /** Max Carry Over Days */
            max_carry_over_days?: number | null;
            /** Carry Over Expiry Months */
            carry_over_expiry_months?: number | null;
        };
        /** LeaveRequestDetail */
        LeaveRequestDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Employee Id
             * Format: uuid
             */
            employee_id: string;
            /** Employee Name */
            employee_name: string;
            /**
             * Leave Type Id
             * Format: uuid
             */
            leave_type_id: string;
            /** Leave Type Code */
            leave_type_code: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /** Days */
            days: number;
            /** Reason */
            reason: string | null;
            status: components["schemas"]["LeaveRequestStatus"];
            /** Approval Levels */
            approval_levels: number;
            /** Current Level */
            current_level: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Approvals */
            approvals: components["schemas"]["LeaveApprovalRead"][];
            /** Warnings */
            warnings: components["schemas"]["TeamOverlapWarning"][];
        };
        /** LeaveRequestInput */
        LeaveRequestInput: {
            /**
             * Leave Type Id
             * Format: uuid
             */
            leave_type_id: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /** Reason */
            reason?: string | null;
        };
        /** LeaveRequestRead */
        LeaveRequestRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Employee Id
             * Format: uuid
             */
            employee_id: string;
            /** Employee Name */
            employee_name: string;
            /**
             * Leave Type Id
             * Format: uuid
             */
            leave_type_id: string;
            /** Leave Type Code */
            leave_type_code: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /** Days */
            days: number;
            /** Reason */
            reason: string | null;
            status: components["schemas"]["LeaveRequestStatus"];
            /** Approval Levels */
            approval_levels: number;
            /** Current Level */
            current_level: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * LeaveRequestStatus
         * @enum {string}
         */
        LeaveRequestStatus: "pending" | "approved" | "rejected" | "cancelled";
        /** LeaveTypeCreate */
        LeaveTypeCreate: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /**
             * Requires Balance
             * @default true
             */
            requires_balance: boolean;
            /**
             * Is Paid
             * @default true
             */
            is_paid: boolean;
            /**
             * Min Notice Days
             * @default 0
             */
            min_notice_days: number;
            /**
             * Allow Backdated
             * @default false
             */
            allow_backdated: boolean;
            /** Max Days Per Request */
            max_days_per_request?: number | null;
            /**
             * Approval Levels
             * @default 1
             */
            approval_levels: number;
        };
        /** LeaveTypeRead */
        LeaveTypeRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Requires Balance */
            requires_balance: boolean;
            /** Is Paid */
            is_paid: boolean;
            /** Min Notice Days */
            min_notice_days: number;
            /** Allow Backdated */
            allow_backdated: boolean;
            /** Max Days Per Request */
            max_days_per_request: number | null;
            /** Approval Levels */
            approval_levels: number;
            /** Is Active */
            is_active: boolean;
        };
        /** LeaveTypeUpdate */
        LeaveTypeUpdate: {
            /** Name */
            name?: string | null;
            /** Is Paid */
            is_paid?: boolean | null;
            /** Min Notice Days */
            min_notice_days?: number | null;
            /** Allow Backdated */
            allow_backdated?: boolean | null;
            /** Max Days Per Request */
            max_days_per_request?: number | null;
            /** Approval Levels */
            approval_levels?: number | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /**
         * LeaveValidationResult
         * @description Hasil dry-run. Hard error memblokir submit, warning hanya informasi.
         */
        LeaveValidationResult: {
            /** Valid */
            valid: boolean;
            /** Days */
            days: number;
            /** Errors */
            errors: components["schemas"]["RuleMessage"][];
            /** Warnings */
            warnings: components["schemas"]["TeamOverlapWarning"][];
            balance: components["schemas"]["BalancePreview"] | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Tenant Slug */
            tenant_slug: string;
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** MeResponse */
        MeResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Roles */
            roles: string[];
            /** Employee Id */
            employee_id: string | null;
            tenant: components["schemas"]["TenantSummary"];
        };
        /** OrgUnitCreate */
        OrgUnitCreate: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Parent Id */
            parent_id?: string | null;
            /** Manager Employee Id */
            manager_employee_id?: string | null;
        };
        /** OrgUnitRead */
        OrgUnitRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Parent Id */
            parent_id: string | null;
            /** Manager Employee Id */
            manager_employee_id: string | null;
            /** Is Active */
            is_active: boolean;
        };
        /**
         * OrgUnitUpdate
         * @description Hanya field yang dikirim yang diubah. Kirim null untuk mengosongkan parent/manager.
         */
        OrgUnitUpdate: {
            /** Name */
            name?: string | null;
            /** Parent Id */
            parent_id?: string | null;
            /** Manager Employee Id */
            manager_employee_id?: string | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** Page[EmployeeJobRead] */
        Page_EmployeeJobRead_: {
            /** Items */
            items: components["schemas"]["EmployeeJobRead"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Page[EmployeeRead] */
        Page_EmployeeRead_: {
            /** Items */
            items: components["schemas"]["EmployeeRead"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Page[HolidayRead] */
        Page_HolidayRead_: {
            /** Items */
            items: components["schemas"]["HolidayRead"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Page[LeavePolicyRead] */
        Page_LeavePolicyRead_: {
            /** Items */
            items: components["schemas"]["LeavePolicyRead"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Page[LeaveRequestRead] */
        Page_LeaveRequestRead_: {
            /** Items */
            items: components["schemas"]["LeaveRequestRead"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Page[LeaveTypeRead] */
        Page_LeaveTypeRead_: {
            /** Items */
            items: components["schemas"]["LeaveTypeRead"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Page[OrgUnitRead] */
        Page_OrgUnitRead_: {
            /** Items */
            items: components["schemas"]["OrgUnitRead"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Page[TeamCalendarItem] */
        Page_TeamCalendarItem_: {
            /** Items */
            items: components["schemas"]["TeamCalendarItem"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** ReadinessChecks */
        ReadinessChecks: {
            /**
             * Database
             * @enum {string}
             */
            database: "ok" | "error";
            /**
             * Redis
             * @enum {string}
             */
            redis: "ok" | "error";
        };
        /** ReadinessResponse */
        ReadinessResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "not_ready";
            checks: components["schemas"]["ReadinessChecks"];
        };
        /** RuleMessage */
        RuleMessage: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** TeamCalendarItem */
        TeamCalendarItem: {
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
            /**
             * Employee Id
             * Format: uuid
             */
            employee_id: string;
            /** Employee Name */
            employee_name: string;
            /** Leave Type Code */
            leave_type_code: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /** Days */
            days: number;
            status: components["schemas"]["LeaveRequestStatus"];
        };
        /** TeamOverlapWarning */
        TeamOverlapWarning: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Colleagues On Leave */
            colleagues_on_leave: number;
        };
        /** TenantSummary */
        TenantSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
        };
        /**
         * TokenResponse
         * @description Access token untuk header Authorization. Refresh token dikirim sebagai cookie httpOnly.
         */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
            /** Expires In */
            expires_in: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Tenant, email, atau password salah */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Terlalu banyak percobaan gagal */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    refresh_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Refresh token tidak valid */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_me_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    list_org_units_org_units_get: {
        parameters: {
            query?: {
                include_inactive?: boolean;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_OrgUnitRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_org_unit_org_units_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrgUnitCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgUnitRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_org_unit_org_units__unit_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                unit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgUnitRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_org_unit_org_units__unit_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                unit_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrgUnitUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgUnitRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_employees_employees_get: {
        parameters: {
            query?: {
                status?: "active" | "terminated" | "pre_hire" | "all";
                org_unit_id?: string | null;
                supervisor_id?: string | null;
                /** @description Tanggal acuan jabatan. Default: hari ini di zona waktu tenant. */
                as_of?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_EmployeeRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_employee_employees_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_employee_employees__employee_id__get: {
        parameters: {
            query?: {
                /** @description Tanggal acuan jabatan. Default: hari ini di zona waktu tenant. */
                as_of?: string | null;
            };
            header?: never;
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_employee_employees__employee_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_employees__employee_id__jobs_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_EmployeeJobRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_job_employees__employee_id__jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeeJobCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeJobRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_leave_types_leave_types_get: {
        parameters: {
            query?: {
                include_inactive?: boolean;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_LeaveTypeRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_leave_type_leave_types_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeaveTypeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaveTypeRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_leave_type_leave_types__type_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                type_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeaveTypeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaveTypeRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_policies_leave_policies_get: {
        parameters: {
            query?: {
                leave_type_id?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_LeavePolicyRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_policy_leave_policies_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeavePolicyCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeavePolicyRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_policy_leave_policies__policy_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                policy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_policy_leave_policies__policy_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                policy_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeavePolicyUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeavePolicyRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_holidays_leave_holidays_get: {
        parameters: {
            query?: {
                year?: number | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_HolidayRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_holiday_leave_holidays_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HolidayCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HolidayRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_holiday_leave_holidays__holiday_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                holiday_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_leave_balance_leave_balances_get: {
        parameters: {
            query?: {
                employee_id?: string | null;
                year?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaveBalanceSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    adjust_leave_balance_leave_balances_adjustments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BalanceAdjustment"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaveBalanceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_leave_request_leave_requests_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeaveRequestInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaveValidationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_leave_requests_leave_requests_get: {
        parameters: {
            query?: {
                scope?: "mine" | "approvals" | "all";
                status?: components["schemas"]["LeaveRequestStatus"] | null;
                year?: number | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_LeaveRequestRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_leave_request_leave_requests_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeaveRequestInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaveRequestDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_leave_request_leave_requests__request_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaveRequestDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_leave_request_leave_requests__request_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeaveCancel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaveRequestDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_leave_request_leave_requests__request_id__decision_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeaveDecision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaveRequestDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_team_calendar_leave_team_calendar_get: {
        parameters: {
            query: {
                start: string;
                end: string;
                org_unit_id?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_TeamCalendarItem_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
