"""job framework and leave carry-over

Tabel job_schedule, job_run, job_run_chunk, job_run_log (ADR 009), kolom carry-over dan hangus
di leave_balance (ADR 010), dan fungsi SECURITY DEFINER untuk scheduler lintas tenant.

Revision ID: 956794f5762d
Revises: 7686c168123e
Create Date: 2026-09-28 02:22:07.974360

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from app.core.tenant import APP_DB_ROLE, grant_statement, rls_statements

# revision identifiers, used by Alembic.
revision: str = "956794f5762d"
down_revision: str | Sequence[str] | None = "7686c168123e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_SCHEDULER_FN_SIGNATURE = "job_scheduler_work(timestamptz, timestamptz, timestamptz, integer)"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_schedule",
        sa.Column("job_code", sa.String(length=64), nullable=False),
        sa.Column("cron", sa.String(length=100), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column(
            "params",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_job_schedule_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_schedule")),
        sa.UniqueConstraint("tenant_id", "id", name="uq_job_schedule_tenant_id_id"),
    )
    op.create_index(
        "uq_job_schedule_tenant_id_job_code", "job_schedule", ["tenant_id", "job_code"], unique=True
    )
    op.create_table(
        "job_run",
        sa.Column("job_code", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("dry_run", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "params",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("trigger", sa.String(length=16), nullable=False),
        sa.Column("schedule_id", sa.Uuid(), nullable=True),
        sa.Column("requested_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=100), nullable=True),
        sa.Column("chunks_total", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("chunks_done", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("chunks_failed", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "output",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'success', 'partial', 'failed', 'cancelled')",
            name=op.f("ck_job_run_status_valid"),
        ),
        sa.CheckConstraint(
            "trigger IN ('user', 'schedule')", name=op.f("ck_job_run_trigger_valid")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "schedule_id"],
            ["job_schedule.tenant_id", "job_schedule.id"],
            name="fk_job_run_schedule",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_job_run_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_run")),
        sa.UniqueConstraint("tenant_id", "id", name="uq_job_run_tenant_id_id"),
    )
    op.create_index(
        "ix_job_run_tenant_id_created", "job_run", ["tenant_id", "created_at", "id"], unique=False
    )
    op.create_index(
        "uq_job_run_active",
        "job_run",
        ["tenant_id", "job_code"],
        unique=True,
        postgresql_where=sa.text("status IN ('queued', 'running')"),
    )
    op.create_index(
        "uq_job_run_idempotency",
        "job_run",
        ["tenant_id", "idempotency_key"],
        unique=True,
        postgresql_where=sa.text("idempotency_key IS NOT NULL"),
    )
    op.create_table(
        "job_run_chunk",
        sa.Column("job_run_id", sa.Uuid(), nullable=False),
        sa.Column("chunk_no", sa.Integer(), nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "output",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'success', 'failed', 'cancelled')",
            name=op.f("ck_job_run_chunk_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "job_run_id"],
            ["job_run.tenant_id", "job_run.id"],
            name="fk_job_run_chunk_run",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_job_run_chunk_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_run_chunk")),
    )
    op.create_index(
        "uq_job_run_chunk_no", "job_run_chunk", ["tenant_id", "job_run_id", "chunk_no"], unique=True
    )
    op.create_table(
        "job_run_log",
        sa.Column("job_run_id", sa.Uuid(), nullable=False),
        sa.Column("chunk_no", sa.Integer(), nullable=True),
        sa.Column("level", sa.String(length=16), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "level IN ('info', 'warning', 'error')", name=op.f("ck_job_run_log_level_valid")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "job_run_id"],
            ["job_run.tenant_id", "job_run.id"],
            name="fk_job_run_log_run",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_job_run_log_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_run_log")),
    )
    op.create_index(
        "ix_job_run_log_run",
        "job_run_log",
        ["tenant_id", "job_run_id", "created_at", "id"],
        unique=False,
    )
    op.add_column(
        "leave_balance", sa.Column("expired", sa.SmallInteger(), server_default="0", nullable=False)
    )
    op.add_column(
        "leave_balance",
        sa.Column("carry_over_applied_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column("leave_balance", sa.Column("carry_over_expires_on", sa.Date(), nullable=True))
    op.add_column(
        "leave_balance",
        sa.Column("carry_over_expired_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###
    op.create_check_constraint(
        op.f("ck_leave_balance_expired_valid"),
        "leave_balance",
        "expired >= 0 AND expired <= carried_over",
    )

    # Scan scheduler lintas tenant (satu-satunya pengecualian index tanpa awalan tenant_id).
    op.create_index(
        "ix_job_schedule_due",
        "job_schedule",
        ["next_run_at"],
        postgresql_where=sa.text("is_active"),
    )
    op.create_index(
        "ix_job_run_active_updated",
        "job_run",
        ["updated_at"],
        postgresql_where=sa.text("status IN ('queued', 'running')"),
    )

    op.execute(grant_statement("job_schedule", "SELECT, INSERT, UPDATE"))
    op.execute(grant_statement("job_run", "SELECT, INSERT, UPDATE"))
    op.execute(grant_statement("job_run_chunk", "SELECT, INSERT, UPDATE"))
    op.execute(grant_statement("job_run_log", "SELECT, INSERT"))  # append-only
    for table in ("job_schedule", "job_run", "job_run_chunk", "job_run_log"):
        for statement in rls_statements(table):
            op.execute(statement)

    # Scheduler perlu melihat pekerjaan semua tenant, tapi role aplikasi tunduk RLS. Fungsi ini
    # berjalan sebagai owner (BYPASSRLS) dan hanya mengembalikan id + tenant_id; pekerjaan
    # selanjutnya dilakukan per tenant di bawah RLS.
    op.execute(
        """
        CREATE FUNCTION job_scheduler_work(
            p_now timestamptz, p_queued_before timestamptz,
            p_stalled_before timestamptz, p_limit integer
        )
        RETURNS TABLE (kind text, tenant_id uuid, id uuid)
        LANGUAGE sql STABLE SECURITY DEFINER
        SET search_path = pg_catalog, public
        AS $$
            (SELECT 'schedule'::text, s.tenant_id, s.id FROM public.job_schedule s
             WHERE s.is_active AND s.next_run_at <= p_now
             ORDER BY s.next_run_at LIMIT p_limit)
            UNION ALL
            (SELECT 'queued'::text, r.tenant_id, r.id FROM public.job_run r
             WHERE r.status = 'queued' AND r.updated_at < p_queued_before
             ORDER BY r.updated_at LIMIT p_limit)
            UNION ALL
            (SELECT 'stalled'::text, r.tenant_id, r.id FROM public.job_run r
             WHERE r.status = 'running' AND r.updated_at < p_stalled_before
             ORDER BY r.updated_at LIMIT p_limit)
        $$
        """
    )
    op.execute(f"REVOKE ALL ON FUNCTION {_SCHEDULER_FN_SIGNATURE} FROM PUBLIC")
    op.execute(f"GRANT EXECUTE ON FUNCTION {_SCHEDULER_FN_SIGNATURE} TO {APP_DB_ROLE}")


def downgrade() -> None:
    op.execute(f"DROP FUNCTION {_SCHEDULER_FN_SIGNATURE}")
    op.drop_index("ix_job_run_active_updated", table_name="job_run")
    op.drop_index("ix_job_schedule_due", table_name="job_schedule")
    op.drop_constraint(op.f("ck_leave_balance_expired_valid"), "leave_balance", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("leave_balance", "carry_over_expired_at")
    op.drop_column("leave_balance", "carry_over_expires_on")
    op.drop_column("leave_balance", "carry_over_applied_at")
    op.drop_column("leave_balance", "expired")
    op.drop_index("ix_job_run_log_run", table_name="job_run_log")
    op.drop_table("job_run_log")
    op.drop_index("uq_job_run_chunk_no", table_name="job_run_chunk")
    op.drop_table("job_run_chunk")
    op.drop_index(
        "uq_job_run_idempotency",
        table_name="job_run",
        postgresql_where=sa.text("idempotency_key IS NOT NULL"),
    )
    op.drop_index(
        "uq_job_run_active",
        table_name="job_run",
        postgresql_where=sa.text("status IN ('queued', 'running')"),
    )
    op.drop_index("ix_job_run_tenant_id_created", table_name="job_run")
    op.drop_table("job_run")
    op.drop_index("uq_job_schedule_tenant_id_job_code", table_name="job_schedule")
    op.drop_table("job_schedule")
    # ### end Alembic commands ###
