"""report template and semantic views

Semantic views untuk report builder (ADR 012). security_invoker = true wajib: tanpa itu view
berjalan dengan hak owner dan melewati RLS. Kolom sensitif (NIK KTP, gaji, rekening) tidak ada.

Revision ID: 6df5ec9c8b50
Revises: b984eef28460
Create Date: 2026-09-29 01:19:34.768711

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from app.core.tenant import APP_DB_ROLE, grant_statement, rls_statements

# revision identifiers, used by Alembic.
revision: str = "6df5ec9c8b50"
down_revision: str | Sequence[str] | None = "b984eef28460"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Jabatan yang berlaku hari ini menurut zona waktu tenant.
V_EMPLOYEE = """
CREATE VIEW v_employee WITH (security_invoker = true) AS
SELECT e.tenant_id,
       e.id AS employee_id,
       e.employee_number,
       e.full_name,
       e.work_email,
       e.hire_date,
       CASE WHEN j.employee_id IS NULL THEN 'pre_hire' ELSE j.employment_status END AS status,
       j.job_title,
       j.grade,
       j.employment_type,
       j.org_unit_id,
       ou.code AS org_unit_code,
       ou.name AS org_unit_name,
       sup.employee_number AS supervisor_number,
       sup.full_name AS supervisor_name,
       j.effdt AS job_effective_date,
       CASE WHEN e.hire_date > d.today THEN 0
            ELSE (EXTRACT(YEAR FROM age(d.today, e.hire_date)) * 12
                  + EXTRACT(MONTH FROM age(d.today, e.hire_date)))::int
       END AS service_months
FROM employee e
JOIN tenant t ON t.id = e.tenant_id
CROSS JOIN LATERAL (SELECT (now() AT TIME ZONE t.timezone)::date AS today) d
LEFT JOIN LATERAL (
    SELECT ej.employee_id, ej.effdt, ej.job_title, ej.grade, ej.employment_type,
           ej.employment_status, ej.org_unit_id, ej.supervisor_employee_id
    FROM employee_job ej
    WHERE ej.tenant_id = e.tenant_id AND ej.employee_id = e.id AND ej.effdt <= d.today
    ORDER BY ej.effdt DESC, ej.effseq DESC
    LIMIT 1
) j ON true
LEFT JOIN org_unit ou ON ou.tenant_id = e.tenant_id AND ou.id = j.org_unit_id
LEFT JOIN employee sup ON sup.tenant_id = e.tenant_id AND sup.id = j.supervisor_employee_id
"""

V_ORG_UNIT = """
CREATE VIEW v_org_unit WITH (security_invoker = true) AS
SELECT ou.tenant_id,
       ou.id AS org_unit_id,
       ou.code,
       ou.name,
       ou.is_active,
       p.code AS parent_code,
       p.name AS parent_name,
       m.employee_number AS manager_number,
       m.full_name AS manager_name,
       COALESCE(hc.active_headcount, 0) AS active_headcount
FROM org_unit ou
LEFT JOIN org_unit p ON p.tenant_id = ou.tenant_id AND p.id = ou.parent_id
LEFT JOIN employee m ON m.tenant_id = ou.tenant_id AND m.id = ou.manager_employee_id
LEFT JOIN (
    SELECT tenant_id, org_unit_id, count(*)::int AS active_headcount
    FROM v_employee
    WHERE status = 'active'
    GROUP BY tenant_id, org_unit_id
) hc ON hc.tenant_id = ou.tenant_id AND hc.org_unit_id = ou.id
"""

V_LEAVE_BALANCE = """
CREATE VIEW v_leave_balance WITH (security_invoker = true) AS
SELECT lb.tenant_id,
       lb.employee_id,
       ve.employee_number,
       ve.full_name,
       ve.status AS employee_status,
       ve.org_unit_code,
       ve.org_unit_name,
       lb.year,
       lt.code AS leave_type_code,
       lt.name AS leave_type_name,
       lb.entitled,
       lb.carried_over,
       lb.adjusted,
       lb.used,
       lb.pending,
       lb.expired,
       (lb.entitled + lb.carried_over + lb.adjusted - lb.used - lb.pending - lb.expired)
           AS available,
       lb.carry_over_expires_on
FROM leave_balance lb
JOIN v_employee ve ON ve.tenant_id = lb.tenant_id AND ve.employee_id = lb.employee_id
JOIN leave_type lt ON lt.tenant_id = lb.tenant_id AND lt.id = lb.leave_type_id
"""

V_LEAVE_REQUEST = """
CREATE VIEW v_leave_request WITH (security_invoker = true) AS
SELECT lr.tenant_id,
       lr.id AS request_id,
       lr.employee_id,
       ve.employee_number,
       ve.full_name,
       ve.org_unit_code,
       ve.org_unit_name,
       lt.code AS leave_type_code,
       lt.name AS leave_type_name,
       lr.start_date,
       lr.end_date,
       lr.days,
       lr.status,
       lr.reason,
       lr.created_at,
       lr.decided_at,
       lr.cancelled_at
FROM leave_request lr
JOIN v_employee ve ON ve.tenant_id = lr.tenant_id AND ve.employee_id = lr.employee_id
JOIN leave_type lt ON lt.tenant_id = lr.tenant_id AND lt.id = lr.leave_type_id
"""

VIEWS = (
    ("v_employee", V_EMPLOYEE),
    ("v_org_unit", V_ORG_UNIT),
    ("v_leave_balance", V_LEAVE_BALANCE),
    ("v_leave_request", V_LEAVE_REQUEST),
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "report_template",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("query", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=100), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_report_template_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_template")),
    )
    op.create_index(
        "uq_report_template_tenant_id_name", "report_template", ["tenant_id", "name"], unique=True
    )
    op.create_index(
        "uq_report_template_idempotency",
        "report_template",
        ["tenant_id", "idempotency_key"],
        unique=True,
        postgresql_where=sa.text("idempotency_key IS NOT NULL"),
    )
    # ### end Alembic commands ###
    op.execute(grant_statement("report_template", "SELECT, INSERT, UPDATE, DELETE"))
    for statement in rls_statements("report_template"):
        op.execute(statement)

    for name, sql in VIEWS:
        op.execute(sql)
        op.execute(f"GRANT SELECT ON {name} TO {APP_DB_ROLE}")


def downgrade() -> None:
    for name, _ in reversed(VIEWS):
        op.execute(f"DROP VIEW {name}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_report_template_idempotency", table_name="report_template")
    op.drop_index("uq_report_template_tenant_id_name", table_name="report_template")
    op.drop_table("report_template")
    # ### end Alembic commands ###
