"""tenant ai setting and usage

Setting AI per tenant dengan API key terenkripsi (BYOK), log pemakaian, dan counter bulanan
untuk limit token (ADR 011).

Revision ID: b984eef28460
Revises: 956794f5762d
Create Date: 2026-09-28 06:48:02.200076

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from app.core.tenant import grant_statement, rls_statements

# revision identifiers, used by Alembic.
revision: str = "b984eef28460"
down_revision: str | Sequence[str] | None = "956794f5762d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_usage",
        sa.Column("feature", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("cached_input_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("output_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_ai_usage_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_usage")),
    )
    op.create_index(
        "ix_ai_usage_tenant_id_created", "ai_usage", ["tenant_id", "created_at"], unique=False
    )
    op.create_table(
        "ai_usage_monthly",
        sa.Column("month", sa.Date(), nullable=False),
        sa.Column("feature", sa.String(length=64), nullable=False),
        sa.Column("calls", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("input_tokens", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "cached_input_tokens", sa.BigInteger(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("output_tokens", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_ai_usage_monthly_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("tenant_id", "month", "feature", name=op.f("pk_ai_usage_monthly")),
    )
    op.create_table(
        "tenant_ai_setting",
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("base_url", sa.String(length=255), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("api_key_ciphertext", sa.Text(), nullable=True),
        sa.Column("api_key_hint", sa.String(length=8), nullable=True),
        sa.Column("key_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "enabled_features",
            postgresql.ARRAY(sa.String(length=64)),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("monthly_token_limit", sa.BigInteger(), nullable=True),
        sa.Column("consent_accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consent_accepted_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "provider IN ('deepseek', 'openai', 'openrouter', 'custom')",
            name=op.f("ck_tenant_ai_setting_provider_valid"),
        ),
        sa.CheckConstraint(
            "monthly_token_limit IS NULL OR monthly_token_limit > 0",
            name=op.f("ck_tenant_ai_setting_limit_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_tenant_ai_setting_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenant_ai_setting")),
    )
    op.create_index(
        "uq_tenant_ai_setting_tenant_id", "tenant_ai_setting", ["tenant_id"], unique=True
    )
    # ### end Alembic commands ###

    # Setting tidak dihapus (key cukup dikosongkan). Log pemakaian append-only.
    op.execute(grant_statement("tenant_ai_setting", "SELECT, INSERT, UPDATE"))
    op.execute(grant_statement("ai_usage", "SELECT, INSERT"))
    op.execute(grant_statement("ai_usage_monthly", "SELECT, INSERT, UPDATE"))
    for table in ("tenant_ai_setting", "ai_usage", "ai_usage_monthly"):
        for statement in rls_statements(table):
            op.execute(statement)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_tenant_ai_setting_tenant_id", table_name="tenant_ai_setting")
    op.drop_table("tenant_ai_setting")
    op.drop_table("ai_usage_monthly")
    op.drop_index("ix_ai_usage_tenant_id_created", table_name="ai_usage")
    op.drop_table("ai_usage")
    # ### end Alembic commands ###
